### PR TITLE
test: Run GitHub actions on `release-*` branches

### PR DESCRIPTION
**Pull request by ckadner**
#### Motivation

When we create a new release we need the GitHub actions to run for 
- Lint
- Unit test
- FVT
- Image build and push

#### Modifications

Update the Github workflow definitions to include any `release-..` branches.

#### Result

The GitHub action run on PR and pushed to the release branch.

As can be seen in this PR targeting the `release-0.10` branch:
https://github.com/kserve/modelmesh-serving/pull/298

/cc @njhill @rafvasq

### CODE REVIEW

**Comment by ckadner** [comment]
Oh, interesting. Seems like the FVT got triggered even though there are no functional changes that should warrant that.

Maybe we need to update the path-ignore expressions 🤔

**Comment by ckadner** [comment]
> Oh, interesting. Seems like the FVT got triggered even though there are no functional changes that should warrant that.
> 
> Maybe we need to update the path-ignore expressions 🤔

Ah, nevermind. The FVTs want to be run when the FVT workflow file gets changed :-)

**Review by rafvasq — APPROVED** [review]

**Comment by ckadner** [comment]
I will open a new PR with just the workflow file changes. The unrelated merge commits should not be in here and might overwrite changes that were done after this PR was created.

**Comment by ckadner** [comment]
New (and improved) PR: #310

**Pull request closed without merging**
