### PR TITLE
feat: Add Template Grafana Dashboard for ModelMesh Metrics

### LINKED ISSUE #335: Pre-built grafana dashboard for modelmesh metrics
There is a grafana dashboard we developed for displaying the various prometheus metrics exposed by modelmesh in a clear/useful manner.

However, it was created originally for "standalone" modelmesh use where there's only a single runtime / Deployment per logical modelmesh service. This means it should work well as-is with modelmesh-serving in cases where only one runtime is used, but needs to be tested and probably adjusted/generalized for multi-runtime use.

Potential issues include the fact that the available memory is assumed to be a single pool available to any model, but with multiple runtimes it could in reality be effectively partitions.

Here is the current exported dashboard json: [ModelMeshMetricsDashboard.json.gz](https://github.com/kserve/modelmesh-serving/files/10839643/ModelMeshMetricsDashboard.json.gz)

### PR DESCRIPTION
**Pull request by rafvasq**
#### Motivation
To port a previously-built Grafana dashboard developed for displaying various prometheus metrics for ModelMesh and build upon it to include metrics at the deployment/runtime-view

#### Modifications
- Added `config/dashboard/` directory to host grafana dashboard JSON
- Added `servicemonitor.yaml` to `config/prometheus/`
- Added and modified `ModelMeshMetricsDashboard.json` to work out-of-the-box 
  - Added queries for deployment views to filter by serving runtime
  - Created sections for global-view and deployment-view visualizations
  - Created drop-down variables for filtering between one or many pre-existing runtimes with option to filter by custom serving runtime
- Updated `monitoring.md` doc to include guide for setting up Prometheus/Grafana for monitoring; mainly using instructions from [modelmesh-performance](https://github.com/kserve/modelmesh-performance/tree/main/docs/monitoring)

#### Result
- A functional, ready-to-use dashboard JSON
- General documentation outlining out to set up monitoring and use the JSON
- Closes #335

### CODE REVIEW

**Comment by rafvasq** [comment]
Screenshot 2023-03-17 at 2 10 40 PM
Screenshot 2023-03-17 at 2 10 51 PM
Screenshot 2023-03-17 at 2 11 10 PM

**Comment by rafvasq** [comment]
Current deployment-view metrics: 
image

**Comment by rafvasq** [comment]
screencapture-localhost-3000-d-123vMm-rt-7z-new-modelmesh-dashboard-3-2023-04-05-15_07_18

**Comment by VedantMahabaleshwarkar** [comment]
Would it be possible to have the dashboard json file in `config/dashboard/` instead of `config/grafana` ? It is possible to take a grafana dashboard json but not use grafana itself to construct the dashboard. This would make the directory more "generic" in my opinion without affecting functionality. 
eg: Openshift 4.11 + takes grafana dashboards json files and reconstructs the dashboard internally in the same UI page without having to use the grafana service.

**Comment by rafvasq** [comment]
@VedantMahabaleshwarkar thanks for pointing that out. I agree `config/dashboard` will generalize the directory holding the JSON and additionally I think that the `servicemonitor.yaml` can be moved to the already-existing `config/prometheus` directory too.

**Review by VedantMahabaleshwarkar — DISMISSED** [review]

**Review by njhill — APPROVED** [review]
Thanks @rafvasq, apologies for taking so long to get to this.

**Comment by njhill** [comment]
@rafvasq I tried rebasing this but it seems to be failing the FVTs for some reason.

**Comment by rafvasq** [comment]
> @rafvasq I tried rebasing this but it seems to be failing the FVTs for some reason.

@njhill Similar problem here https://github.com/kserve/modelmesh-serving/pull/359/#issuecomment-1565050430 but all passing now that the MLServer PR is in

**Review by njhill — APPROVED** [review]

**Pull request merged**
