### PR TITLE
fix: set non-empty modelPath for http storageURI

### PR DESCRIPTION
**Pull request by tjohnson31415**
#### Motivation

When using the `storageURI` form of an HTTP (non Azure blob) address to download a model, the `modelPath` needs to be an non-empty string. Before this change, the `storageURI: http://models.r.us/my-model.json` form would be equivalent to the following `storage` spec:
```
storage:
  type: http
  path: ''    # this being empty is problematic for later processing
  parameters:
    url: http://models.r.us/path/to/my-model.json      
```

The http storage type is currently the only way to have a valid storage configuration with an empty `path` (mainly because it has a "url" parameter that could include the full path). That said, I'm not sure if we should make a `path` required for the HTTP storage type. In particular, if the `url` is just `http://models.r.us/`, there is no path portion.

Related: https://github.com/kserve/modelmesh-runtime-adapter/issues/41#issuecomment-1564909111

#### Modifications

Set `modelPath` to the URL's Path and set the `url` parameter to not have the URL Path.

#### Result

With these changes, the `storageURI` example above changes to have a `path` field:

```
storage:
  type: http
  path: path/to/my-model.json
  parameters:
    url: http://models.r.us/
```

### CODE REVIEW

**Comment by tjohnson31415** [comment]
The changes in this PR are dependent on a fix in https://github.com/kserve/modelmesh-runtime-adapter/pull/52 to not duplicate the "local path" for the downloaded file. Using the example from the issue description, without the fix in https://github.com/kserve/modelmesh-runtime-adapter/pull/52,  the file will be downloaded as `my-model.json/my-model.json`.

**Comment by ckadner** [comment]
I created a small FVT test case for this. I was about to push it to your branch assuming you will be away for a while.

Do you mind me adding it to your PR, or did you already have one ready?

**Comment by ckadner** [comment]
The FVT completed successfully after the [modelmesh-runtime-adapter](https://hub.docker.com/r/kserve/modelmesh-runtime-adapter/tags) image was built and pushed to DockerHub

https://github.com/kserve/modelmesh-serving/actions/runs/5150015048/jobs/9274211815#step:15:2367

```YAML
------------------------------
• [2.413 seconds]
ISVCs with HTTPS storage URI should successfully load a model
/home/runner/work/modelmesh-serving/modelmesh-serving/fvt/storage/storage_test.go:59

  Timeline >>
  STEP: Creating inference service isvc-https-z7s2q @ 06/02/23 00:02:40.939
  STEP: Waiting for inference service isvc-https-z7s2q to be 'Ready' and model is 'Loaded' @ 06/02/23 00:02:40.953
  << Timeline
------------------------------
• [0.063 seconds]
ISVCs with HTTPS storage URI should successfully run inference
/home/runner/work/modelmesh-serving/modelmesh-serving/fvt/storage/storage_test.go:65

  Timeline >>
  2023-06-02T00:02:43Z	INFO	Deleting inference services isvc-https-z7s2q
  << Timeline
------------------------------
```

**Review by ckadner — APPROVED** [review]
Thank you @tjohnson31415 for working on these two fixes despite being on leave!

/lgtm

**Pull request merged**
