### PR TITLE
fvt: a bunch of FVT improvements

### PR DESCRIPTION
**Pull request by tjohnson31415**
#### Motivation

A bunch of improvements to the FVT framework coming from our internal fork.

After parallelizing and expanding the FVT suite to support testing the REST proxy internally, we had issues with the consistency of the FVTs. It took a few iterations of improvements to get them back to stable while we continued to add support for more tests. With the "fixes" and "features" coupled in a few different PRs the changes cannot be easily disentangled. This is a big mess of a PR, but the final result should be in a good place with all of our internal improvements.

#### Modifications

Test Parallelization:
- split FVTs into separate suites (go packages)
  - ginkgo can parallelize within a suite, but runs the suites sequentially
- refactors to enable sharing of code across the FVT suites
- support parallelization by using `ginkgo` CLI to execute the tests instead of `go test`
- use Ordered/Serial decorators on groups of tests that require it
  - this can help to speed up "inference" tests by creating the predictor once and using it across multiple specs, but it does mean some specs are not independent
  - TLS tests are marked as Serial because they require roll outs of the runtime pods
- to help debugging, print inference services on failure in Predictor FVTs
- avoid a nil pointer dereference that can occur if FVTs error during initialization while running in parallel
- remove sleep in AfterEach of TLS tests
- update port-forwards to select a pod directly from the Endpoints object corresponding to the service
  - when port-forwarding to a Service, there is no guard against selecting a Terminating pod

Config and Secrets:
- specify the full DefaultConfig in code instead of in the user-configmap.yaml file
- allow TLS config maps to be overlayed on the base config (instead of template string in YAML)
- generate TLS certificates for each run of the FVTs instead of using hard-coded certs

REST Proxy Tests:
- enable the REST proxy for FVTs and add inference tests using proxy
- have the FVT Client manage port-forwards for each of REST and gRPC

#### Result

- a faster and more efficient FVT suite with parallelization
- improved FVT stability and extensibility to support future changes

### CODE REVIEW

**Comment by chinhuang007** [comment]
It fails in IKS FVT tests with the following:

```
Predictor TLS XGBoost inference
  should successfully run an inference with basic TLS
  /artifacts/fvt/predictor/predictor_test.go:764
------------------------------
• [FAILED] [124.950 seconds]
Predictor
/artifacts/fvt/predictor/predictor_test.go:117
  TLS XGBoost inference
  /artifacts/fvt/predictor/predictor_test.go:756
    [It] should successfully run an inference with basic TLS
    /artifacts/fvt/predictor/predictor_test.go:764

 ....
        [AfterAll] TLS XGBoost inference
      /artifacts/fvt/predictor/predictor_test.go:760
  << End Captured GinkgoWriter Output

  Timeout before deploy 'modelmesh-serving-triton-2.x' ready(last state was replicas: '2' updatedReplicas: '1' availableReplicas: '1')
  Expected
      <bool>: false
  to be true
  In [It] at: /artifacts/fvt/helpers.go:355
```

**Comment by chinhuang007** [comment]
Got a different error this morning:

`Will run 119 of 119 specs
Running in parallel across 4 processes
------------------------------
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] [FAILED] [124.513 seconds]
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59

  Begin Captured GinkgoWriter Output >>
    [SynchronizedBeforeSuite] TOP-LEVEL
      /artifacts/fvt/predictor/predictor_suite_test.go:59
    1.6523693407174776e+09	INFO	Initializing test suite
    1.6523693407175379e+09	INFO	Using environment variables	{"NAMESPACE": "modelmesh-serving", "SERVICENAME": "modelmesh-serving", "CONTROLLERNAMESPACE": "modelmesh-serving"}
    1.6523693407187366e+09	INFO	FVTClientInstance created	{"client": {"Interface":{}}}
    1.6523693408900678e+09	INFO	Delete all predictors ...
    1.6523693429614565e+09	INFO	Delete all inference services ...
    1.6523693452346163e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-ovms-1.x", "status.replicas": 1, "status.availableReplicas": 0, "status.updatedReplicas": 1}
    1.6523693452419176e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-mlserver-0.x", "status.replicas": 1, "status.availableReplicas": 0, "status.updatedReplicas": 1}
    1.6523693452490687e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-triton-2.x", "status.replicas": 1, "status.availableReplicas": 0, "status.updatedReplicas": 1}
    1.652369351184308e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-triton-2.x", "status.replicas": 1, "status.availableReplicas": 1, "status.updatedReplicas": 1}
    1.6523693511843557e+09	INFO	deployStatusesReady: map[modelmesh-serving-mlserver-0.x:false modelmesh-serving-ovms-1.x:false modelmesh-serving-triton-2.x:true]
    1.6523693530798302e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-ovms-1.x", "status.replicas": 1, "status.availableReplicas": 1, "status.updatedReplicas": 1}
    1.6523693530800393e+09	INFO	deployStatusesReady: map[modelmesh-serving-mlserver-0.x:false modelmesh-serving-ovms-1.x:true modelmesh-serving-triton-2.x:true]
  << End Captured GinkgoWriter Output

  Timeout before deploy 'modelmesh-serving-ovms-1.x' ready(last state was replicas: '1' updatedReplicas: '1' availableReplicas: '1')
  Expected
      <bool>: false
  to be true
  In [SynchronizedBeforeSuite] at: /artifacts/fvt/helpers.go:355
------------------------------
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] [FAILED] [124.519 seconds]
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59

  SynchronizedBeforeSuite failed on Ginkgo parallel process #1
    The first SynchronizedBeforeSuite function running on Ginkgo parallel process
    #1 failed.  This suite will now abort.

  
  In [SynchronizedBeforeSuite] at: /artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] [FAILED] [124.547 seconds]
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59

  SynchronizedBeforeSuite failed on Ginkgo parallel process #1
    The first SynchronizedBeforeSuite function running on Ginkgo parallel process
    #1 failed.  This suite will now abort.

  
  In [SynchronizedBeforeSuite] at: /artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] [FAILED] [124.565 seconds]
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59

  SynchronizedBeforeSuite failed on Ginkgo parallel process #1
    The first SynchronizedBeforeSuite function running on Ginkgo parallel process
    #1 failed.  This suite will now abort.

  
  In [SynchronizedBeforeSuite] at: /artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedAfterSuite] `

**Comment by chinhuang007** [comment]
Re-post the error I got this morning. Looks like we could not get the initial setup complete in time. Maybe increase timeForStatusToStabilize?

`Running Suite: Predictor suite - /artifacts/fvt/predictor
=========================================================
Random Seed: 1652369280

Will run 119 of 119 specs
Running in parallel across 4 processes
------------------------------
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] [FAILED] [124.513 seconds]
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59

  Begin Captured GinkgoWriter Output >>
    [SynchronizedBeforeSuite] TOP-LEVEL
      /artifacts/fvt/predictor/predictor_suite_test.go:59
    1.6523693407174776e+09	INFO	Initializing test suite
    1.6523693407175379e+09	INFO	Using environment variables	{"NAMESPACE": "modelmesh-serving", "SERVICENAME": "modelmesh-serving", "CONTROLLERNAMESPACE": "modelmesh-serving"}
    1.6523693407187366e+09	INFO	FVTClientInstance created	{"client": {"Interface":{}}}
    1.6523693408900678e+09	INFO	Delete all predictors ...
    1.6523693429614565e+09	INFO	Delete all inference services ...
    1.6523693452346163e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-ovms-1.x", "status.replicas": 1, "status.availableReplicas": 0, "status.updatedReplicas": 1}
    1.6523693452419176e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-mlserver-0.x", "status.replicas": 1, "status.availableReplicas": 0, "status.updatedReplicas": 1}
    1.6523693452490687e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-triton-2.x", "status.replicas": 1, "status.availableReplicas": 0, "status.updatedReplicas": 1}
    1.652369351184308e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-triton-2.x", "status.replicas": 1, "status.availableReplicas": 1, "status.updatedReplicas": 1}
    1.6523693511843557e+09	INFO	deployStatusesReady: map[modelmesh-serving-mlserver-0.x:false modelmesh-serving-ovms-1.x:false modelmesh-serving-triton-2.x:true]
    1.6523693530798302e+09	INFO	Watcher got event with object	{"name": "modelmesh-serving-ovms-1.x", "status.replicas": 1, "status.availableReplicas": 1, "status.updatedReplicas": 1}
    1.6523693530800393e+09	INFO	deployStatusesReady: map[modelmesh-serving-mlserver-0.x:false modelmesh-serving-ovms-1.x:true modelmesh-serving-triton-2.x:true]
  << End Captured GinkgoWriter Output

  Timeout before deploy 'modelmesh-serving-ovms-1.x' ready(last state was replicas: '1' updatedReplicas: '1' availableReplicas: '1')
  Expected
      <bool>: false
  to be true
  In [SynchronizedBeforeSuite] at: /artifacts/fvt/helpers.go:355
------------------------------
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] [FAILED] [124.519 seconds]
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59

  SynchronizedBeforeSuite failed on Ginkgo parallel process #1
    The first SynchronizedBeforeSuite function running on Ginkgo parallel process
    #1 failed.  This suite will now abort.

  
  In [SynchronizedBeforeSuite] at: /artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] [FAILED] [124.547 seconds]
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59

  SynchronizedBeforeSuite failed on Ginkgo parallel process #1
    The first SynchronizedBeforeSuite function running on Ginkgo parallel process
    #1 failed.  This suite will now abort.

  
  In [SynchronizedBeforeSuite] at: /artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedBeforeSuite] [FAILED] [124.565 seconds]
[SynchronizedBeforeSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:59

  SynchronizedBeforeSuite failed on Ginkgo parallel process #1
    The first SynchronizedBeforeSuite function running on Ginkgo parallel process
    #1 failed.  This suite will now abort.

  
  In [SynchronizedBeforeSuite] at: /artifacts/fvt/predictor/predictor_suite_test.go:59
------------------------------
[SynchronizedAfterSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:87
------------------------------
[SynchronizedAfterSuite] PASSED [0.000 seconds]
[SynchronizedAfterSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:87

  Begin Captured GinkgoWriter Output >>
    [SynchronizedAfterSuite] TOP-LEVEL
      /artifacts/fvt/predictor/predictor_suite_test.go:87
  << End Captured GinkgoWriter Output
------------------------------
[SynchronizedAfterSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:87
------------------------------
[SynchronizedAfterSuite] PASSED [0.000 seconds]
[SynchronizedAfterSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:87

  Begin Captured GinkgoWriter Output >>
    [SynchronizedAfterSuite] TOP-LEVEL
      /artifacts/fvt/predictor/predictor_suite_test.go:87
  << End Captured GinkgoWriter Output
------------------------------
[SynchronizedAfterSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:87
------------------------------
[SynchronizedAfterSuite] PASSED [0.000 seconds]
[SynchronizedAfterSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:87

  Begin Captured GinkgoWriter Output >>
    [SynchronizedAfterSuite] TOP-LEVEL
      /artifacts/fvt/predictor/predictor_suite_test.go:87
  << End Captured GinkgoWriter Output
------------------------------
[SynchronizedAfterSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:87
------------------------------
[SynchronizedAfterSuite] PASSED [0.288 seconds]
[SynchronizedAfterSuite] 
/artifacts/fvt/predictor/predictor_suite_test.go:87

  Begin Captured GinkgoWriter Output >>
    [SynchronizedAfterSuite] TOP-LEVEL
      /artifacts/fvt/predictor/predictor_suite_test.go:87
    [SynchronizedAfterSuite] TOP-LEVEL
      /artifacts/fvt/predictor/predictor_suite_test.go:87
    1.6523694654149373e+09	INFO	Restarting 'modelmesh-serving-mlserver-0.x'
    1.6523694654534466e+09	INFO	Restarting 'modelmesh-serving-ovms-1.x'
    1.6523694654852588e+09	INFO	Restarting 'modelmesh-serving-triton-2.x'
  << End Captured GinkgoWriter Output
------------------------------


Summarizing 4 Failures:
  [FAIL] [SynchronizedBeforeSuite] 
  /artifacts/fvt/predictor/predictor_suite_test.go:59
  [FAIL] [SynchronizedBeforeSuite] 
  /artifacts/fvt/predictor/predictor_suite_test.go:59
  [FAIL] [SynchronizedBeforeSuite] 
  /artifacts/fvt/predictor/predictor_suite_test.go:59
  [FAIL] [SynchronizedBeforeSuite] 
  /artifacts/fvt/helpers.go:355

Ran 0 of 119 Specs in 124.815 seconds
FAIL! - Interrupted by Other Ginkgo Process -- A BeforeSuite node failed so all tests were skipped.`

**Comment by chinhuang007** [comment]
Good news, changing to a different/bigger cluster helps to complete the FVT tests. However the check for a successful test needs to be updated for ginkgo command.

Can you replace l54-l64 in test-fvt.sh with the following? I will try another e2e run with the change. Thanks!

`  if [[ $(grep "Test Suite Passed" fvt.out) ]]; then
    export NAMESPACE="modelmesh-user"
    ginkgo -v --progress --fail-fast -p fvt/predictor fvt/scaleToZero --timeout 40m > fvt.out
    cat fvt.out
    if [[ $(grep "Test Suite Passed" fvt.out) ]]; then
      REV=0
    fi
  fi`

**Review by chinhuang007 — APPROVED** [review]
Looks good! Thanks for making FVT improvements.

**Review by njhill — APPROVED** [review]

**Pull request merged**
