### PR TITLE
fix: Tolerate kustomize version 3.2

### LINKED ISSUE #66: Installer from quick start guide yields an error
While trying to run through the quick start guide, the install script runs into an error

1. `kubectl create namespace modelmesh-serving`
`./scripts/install.sh --namespace modelmesh-serving --quickstart`
2. Wait for installer to run
3. See the following error
```
Installing ModelMesh Serving built-in runtimes
Error: unknown flag: --load-restrictor
error: no objects passed to apply

```

**Expected behavior**

I expect the installer in the quick start guide to run without errors with the provided instructions.

Output from installer run attached.

[mminstall.txt](https://github.com/kserve/modelmesh-serving/files/7428991/mminstall.txt)

**Environment:**

Client Version: 4.5.0-202005291417-9933eb9
Server Version: 4.9.0-rc.5
Kubernetes Version: v1.22.0-rc.0+8719299

**Additional context**
Running on OpenShift 4.9

### PR DESCRIPTION
**Pull request by ckadner**
#### Motivation

Developers who work on both Kubeflow and ModelMesh must use different versions of the `kustomize` CLI as Kubeflow installation requires version no greater than `3.2.0` yet ModelMesh installation requires a version greater than `4.0.0`.

There have been previous changes to the install scripts attempting to tolerate older `kustomize` versions, yet for `3.2` it is still causing errors like these:

```
...
Installing ModelMesh Serving built-in runtimes
Error: unknown flag: --load-restrictor
error: no objects passed to apply
```

This is because various versions of `kustomize` produce differently formatted output and the ModelMesh install scripts do not capture the intended semantic version identifier, i.e.

```Bash
$ kustomize version  # 3.2

Version: {KustomizeVersion:3.2.0 GitCommit:a3103f1e62ddb5b696daa3fd359bb6f2e8333b49 BuildDate:2019-09-18T16:26:36Z GoOs:darwin GoArch:amd64}

$ kustomize version | awk -F'kustomize/' '{print $2}'


# notice nothing here
```

```Bash
$ kustomize version  # 3.4

{Version:kustomize/v3.4.0 GitCommit:2c9635967a2b1469d605a91a1d040bd27c73ca7d BuildDate:2019-11-12T05:00:57Z GoOs:darwin GoArch:amd64}

$ kustomize version | awk -F'kustomize/' '{print $2}'

v3.4.0 GitCommit:2c9635967a2b1469d605a91a1d040bd27c73ca7d BuildDate:2019-11-12T05:00:57Z GoOs:darwin GoArch:amd64}

```

#### Modifications

Change the install (and delete) scripts to `grep` only the semantic version and use that to choose the correct install command syntax.

#### Result

Installation (and de-installation) works for `kustomize` versions `3.2.0` up to latest (currently `4.5.7`)

#### Related Issues:

Fixes #66

### CODE REVIEW

**Comment by ckadner** [comment]
@njhill -- I seem to not have much luck with FVT tests :-)  

It does not seem to be related to my script changes.

**Review by njhill — APPROVED** [review]
Thanks @ckadner. The tests passed after being re-run. I have a feeling the failures were related to the tests being run from multiple PRs concurrently. I don't remember if we have any mutual exclusion for this.

**Comment by ckadner** [comment]
Thanks @njhill

**Pull request merged**
