### PR TITLE
chore: Update TorchServe to 0.7.1

### LINKED ISSUE #360: Update TorchServe serving runtime image
Currently using TorchServe image version 0.6.0-cpu, and [the latest release is 0.7.1](https://github.com/pytorch/serve/releases/tag/v0.7.1).

### PR DESCRIPTION
**Pull request by rafvasq**
#### Motivation
The default TorchServe serving runtime in ModelMesh uses v0.6.0 from May 2022. The [latest version is v0.7.1](https://github.com/pytorch/serve/releases/tag/v0.7.1).

#### Modifications
- TorchServe image version in the default serving runtime and FVTs were updated from 0.6.0 to 0.7.1
- FVT tests for TorchServe were *temporarily* enabled (and OVMS disabled) to confirm they pass 

#### Result
- The default TorchServe serving runtime will now deploy using the 0.7.1 image.
- Closes #360

### CODE REVIEW

**Comment by ckadner** [comment]
@rafvasq -- the FVT check is failing for lack of disk space on the GitHub action runner node.
```
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/local/lib64/python3.8/site-packages/tensorflow/libtensorflow_cc.so.2: no space left on device
Error: Process completed with exit code 1.
```

This should be fixed once PR #368 is merged

**Review by njhill — APPROVED** [review]
Thanks @rafvasq

**Review by ckadner — APPROVED** [review]
/lgtm

**Comment by ckadner** [comment]
Thanks @rafvasq

**Pull request merged**
