### PR TITLE
feat: use ServingRuntime types from kserve/kserve

### PR DESCRIPTION
**Pull request by tjohnson31415**
#### Motivation

We are working to align the CRDs between this repo and kserve/kserve. KServe will be the source-of-truth.

#### Modifications

- update kserve/kserve dependency to latest version (with latest CRD updates)
- refactor to import ServingRuntime and ClusterServingRuntime types from KServe
- continue to generate ServingRuntime and ClusterServingRuntime CRDs by updating the `make manifests` target to generate from KServe

### CODE REVIEW

**Comment by tjohnson31415** [comment]
Converting to Draft as we are proceeding with mirroring changes from `kserve/kserve` until https://github.com/kserve/kserve/pull/2147 can be merged. Doing this unblocks PRs to `modelmesh-serving` that implement features based on the CRD changes being proposed in `kserve/kserve`.

**Comment by pvaneck** [comment]
FYI https://github.com/kserve/kserve/pull/2147 has now been merged

**Comment by tjohnson31415** [comment]
The dependent https://github.com/kserve/kserve/pull/2147 PR has been merged, so I have rebased and updated this branch.

**Review by njhill — APPROVED** [review]
Thanks @tjohnson31415!

**Pull request merged**
