### PR TITLE
Add Makefile documentation

### PR DESCRIPTION
**Pull request by ddelange**
#### Motivation

https://github.com/kserve/modelmesh-runtime-adapter/pull/38#discussion_r1193083493

#### Modifications

Double hashtag just above the target

#### Result

```
all                       - Alias for `manager`
build                     - Build runtime docker image
check-doc-links           - Check markdown files for invalid links
controller-gen            - Find or download controller-gen
deploy                    - Deploy controller in a k8s cluster
deploy-release            - Deploy release (artifactory creds set via env var)
deploy-release-dev-mode   - Deploy release in dev mode (artifactory creds set via env var)
develop                   - Build develop docker image and run an interactive shell in the develop envionment
docker-build              - Build the docker image
docker-push               - Push the docker image
fmt                       - Run go fmt against code
fvt                       - Run fvt tests. This requires an etcd, kubernetes connection, and model serving installation. Ginkgo CLI is used to run them in parallel
fvt-protoc                - Regenerate the grpc go files from the proto files
fvt-with-deploy           - Alias for `oc-login, deploy-release-dev-mode, fvt`
generate                  - Generate code
help                      - Print Makefile documentation
install                   - Install CRDs into a k8s cluster
manager                   - Build manager binary
manifests                 - Generate manifests e.g. CRD, RBAC etc.
mmesh-codegen             - Model Mesh gRPC codegen
oc-login                  - Login
run                       - Build develop docker image and run a make command in the develop envionment (e.g. `make run fmt` will execute `make fmt` within the docker container)
start                     - Run against a k8s cluster
test                      - Run unit tests
uninstall                 - Uninstall CRDs from a k8s cluster
```

### CODE REVIEW

**Comment by ddelange** [comment]
cc @ckadner

**Comment by ckadner** [comment]
> cc @ckadner

Thanks @ddelange this is great. I will add a more detailed review soon.

**Comment by ckadner** [comment]
Hi @ddelange apologies for the long wait. I added a quick review to the sister PR here https://github.com/kserve/modelmesh-runtime-adapter/pull/50

**Comment by ckadner** [comment]
@ddelange -- while syncing with the `main` branch I noticed a few missing help texts and took the opportunity to "harmonize" some of the Make target's names. Could you take another looks to make sure I did not break anything? :-)

**Comment by ddelange** [comment]
awesome!

[https://http.cat/202](https://http.cat/202)

**Pull request merged**
